### ISSUE TITLE
Provide some guidance and reference resources on our documentation page

### ISSUE THREAD

**Issue by gjlawran** [bcgov/api-services-portal#129]
As an  API  owner I would like to easily find some guidance and references to help me and my team know how to design APIs that are consistent and follow good patterns.  I

This 
https://api-gov-bc-ca.test.api.gov.bc.ca/docs

might be a great place to find somethings like ....

https://developer.gov.bc.ca/Data-and-APIs/BC-Government-API-Guidelines

https://api.canada.ca/

https://oai.github.io/Documentation/

**Comment by ashwin-lunkad** [comment]
Accommodate into a single card possibly. May be import a markdown - BC Gov API Guidelines

**Comment by mwendowsky** [comment]
Carol-Anne to add resources to retype with short descriptions

**Comment by CABCGov** [comment]
Not sure what else needs to be added here? Are these the only four resources? Am I looking for others (if yes, what is an indicator that they are good sites)?

**Comment by ikethecoder** [comment]
@CABCGov You can add this new document here: https://github.com/bcgov/aps-infra-platform/tree/test/documentation

You can clone "glossary.md" and use that as a base for this new "References" (?) page.

**Comment by CABCGov** [comment]
@ikethecoder and @jTendeck, I have finished creating the Resources.md file at the link in Aidan's comment. Let me know if you want any changes or prefer different wording or any other items added.

**Comment by jTendeck** [comment]
Hey @CABCGov - The only thing we may want to change is the links. If we want to use `target=blank` to open links in a new tab when you click on them, we can use HTML for the links instead of markdown. For example, using the first link, you can use:

```html
<a href="https://api.canada.ca/" target="_blank">Government of Canada API Store</a>
```
Which produces a link like:

<a href="https://api.canada.ca/" target="_blank">Government of Canada API Store</a>

(Note: this will not open links in a new tab in GitHub, but it does do that in our Retype docs)

So we ma want to replace the links in the document using that format instead.

**Comment by ikethecoder** [comment]
New content has been published: https://bcgov.github.io/aps-infra-platform/resources/
