### ISSUE TITLE
Client is enabled even if approval request is failed and default scopes are removed from Keycloak

### ISSUE THREAD

**Issue by pankaj-cgi** [bcgov/api-services-portal#137]
# API Services Portal Issue

API gateway deletes the default scopes from Keycloak

### ENV

- [ ] `DEV`
- [x ] `TEST`
- [ ] `PROD`

### TESTCASE
Same issuer as mentioned in https://github.com/bcgov/api-services-portal/issues/136

Process: Developer requesting for API
1. Client is created with default scopes
![default_client_scopes](https://user-images.githubusercontent.com/79924447/127051002-b7d291e3-213f-4233-bab2-44fa7a7ab1e6.JPG)

Process: Approver approving the request
Q 1: Request approval failed when approver selected the available scope
![selected-scope-approval-failed](https://user-images.githubusercontent.com/79924447/127051088-bd114b00-ff41-4d75-90bc-6f34aecef680.JPG)

Q 2: Client enabled even if approval failed
![approval-failed-but-client-enabled](https://user-images.githubusercontent.com/79924447/127051152-7ab79e8e-8943-4fb9-9305-8189a782e141.JPG)

Q 3:  request approved when only empty 'Roles' is selected but this lead to removal of default scopes for client
![selected-blank-role-request-approved](https://user-images.githubusercontent.com/79924447/127051256-dd1195bf-d628-4eb6-a1ee-cc1bdda17e28.JPG)

default scopes are removed 
![default-scopes-removed-after-apporval](https://user-images.githubusercontent.com/79924447/127051346-aad943ec-cd3a-4bf3-9857-58969b4b987e.JPG)

-

### EXPECTED

1. Assign selected scope to the client with default scopes
2. Client not enabled when approval process is failed

-

### ACTUAL
1 Removes the default scopes
2 Does not assign the selected scope
3 Approval request is failed (https://github.com/bcgov/api-services-portal/issues/136)
4 Client is enabled even if approval is failed
-

**Comment by ikethecoder** [comment]
Current behaviour is that the Portal assumes it is managing all Scopes for the clients that it creates.. so any Scope the client has that the Portal is not expecting, gets deleted. And the Full Scope Allowed is turned off. The reasoning behind this was to avoid having two administration points for Clients created by the Portal.

There is a bug here though, in that the approved operation should either fully succeed or fully fail, rather than now where the Client is in a partial state of "Enabled with no Scopes assigned".
