### ISSUE TITLE
Confusing message content when running Namespace report

### ISSUE THREAD

**Issue by JohnathanBrammall** [bcgov/api-services-portal#322]
When a namespace manager (Janis) runs a namespace report the displayed message content is confusing. The existing message content intended to be shown when using the namespace menu option to delete a namespace is dissuading users from running namespace reports in order to see namespace metrics and activity.

![image.png](https://images.zenhubusercontent.com/5cb50c356742ff311924d662/f598a419-eced-415d-b88b-df31f02c8571)

Definition of Done: Improve messaging to be appropriate for running a namespace report or remove the existing messaging when the user selects the namespace report option.

**Tasks**

* [x] Prototype first iteration
* [x] Usability Testing 
* [x] Prototype revision
* [ ] Implementation

**Comment by elisafw-ux** [comment]
![Namespace Actions in Header.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/2aacd805-77de-4d9e-a389-a9fa75b31c91)

![Screen Shot 2022-03-11 at 3.11.39 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/b3666e10-5683-44e0-b234-3418af0cacff)

The purpose of this modal is for users to be able to export reports as their main action. The current modal design allows users to delete a namespace and export reports under a modal called "Manage Namespace" 

Currently at the namespace level, a user is capable of managing a namespace including things like granting access, and configuring a namespace. 

The current title "Manage Namespace" on the modal is misleading because users expect its behaviour to be consistent with the Manage Namespace at the namespace level, which it isn't. 

The solution is to make the modal's main purpose to be for exporting reports only, and remove the action to delete namespaces at that level. A user can delete a namespace at the namespace level, making  accidents harder to occur and keeping users a little further away from danger. 

The loading state has changed from a spinner to a progress indicator bar to provide a sense of time and making waiting more tolerable.

**Comment by elisafw-ux** [comment]
@JohnathanBrammall  please review - will move ticket to development if this is good to go

**Comment by JohnathanBrammall** [comment]
@elisafw-ux this is good to move ahead to development

**Comment by elisafw-ux** [comment]
@Jonesy  this is ready for development. The designs are in the handoff page - called "Nav Bar Header - Namespace Actions" under the "Other" section

**Comment by JohnathanBrammall** [comment]
Agreed, ready for development. The design looks great!

**Comment by JohnathanBrammall** [comment]
Moving to Product Backlog for implementation prioritization.

**Comment by Jonesy** [comment]
The UI is ready to integrate with the API endpoint, just need to confirm the following with @ikethecoder 

1. How should I send the selected namespaces to the download URL? Will a search param work, ie. `/endpoint?ids=1,2,3`
1. If we select all namespaces, should I just omit sending IDs and assume empty means all?

Also @elisafw-ux I've modified the layout a little and added some new functionality that lets the user clear the selections if it's not all of them so they don't have to cycle the select all toggle twice to clear. I also found the select all checkbox with no label felt a little cryptic, and the label helps with accessibility

![image.png](https://images.zenhubusercontent.com/5c58b4fbecb0076f3e898867/d9dba775-590d-47cc-a6eb-1f829a7666dd)

**Comment by elisafw-ux** [comment]
@Jonesy that's fine, just a few comments on the padding and text size
1. top padding of the description text should be closer to the header - chakra-space 4
2. text size is 16px for all, except header
3. colour of description text is #606060
4. if it's possible, add a little space between the checkbox and the text - I am thinking chakra-space 2.5

**Comment by Jonesy** [comment]
Fixed and pushed @elisafw-ux ! The padding is 4 between the title and the description, should I shrink it more?

**Comment by Jonesy** [comment]
Don't send all ID's if all namespaces are selected and include auth token in request. Sort alphabetically.

**Comment by elisafw-ux** [comment]
> Fixed and pushed @elisafw-ux ! The padding is 4 between the title and the description, should I shrink it more?

Maybe try 3. We want the description to be closer to the header than the elements underneath
