### ISSUE TITLE
Namespace Org Warning Message

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#386]
Provide a warning message on the Namespace when the namespace has not been associated yet to a Namespace:

![image.png](https://images.zenhubusercontent.com/5c3e5c85cff96b450939aec6/12c64b6e-0891-4d8b-a575-dc05bd3fe4d5)

**Comment by elisafw-ux** [comment]
Since the hierarchical access feature hasnt been implemented yet, we will provide this message in the meantime:
![Screen Shot 2022-05-17 at 1.10.28 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/2543b44a-749f-44a8-ad57-9e47566a0973)
The link goes to JSM, but we don't have a link to the form yet. I'll provide the JSM link once I have it.

**Comment by Jonesy** [comment]
This copy differs slightly from the Figma's, which one should I use? Also let me know the JSM link.

**Comment by elisafw-ux** [comment]
Use this one for now

![Screen Shot 2022-05-25 at 5.38.47 PM.png](https://images.zenhubusercontent.com/60e49e0b04ce244aabe10974/9906d5cb-0670-4c54-ab4c-a747905e8387)

until we have the hierarchical access implemented
