### ISSUE TITLE
Hard delete of Namespace (/namespaces/{ns}?force=true) cause the application inaccessible (throws 502 Bad Gateway Error)

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/api-services-portal#459]
Step 1: Hard delete a namespace that has some services associated with it
Step 2: Verify that other services and aps portal is still running without any issue

![image.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/d279f428-91a8-49fc-b155-7cb8b2a825fe)

![image.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/25ce4102-bd81-4729-a71a-1c1a32fbb59c)

![image.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/904d3f43-49f1-4bc7-ba98-6e48c1e9e716)

![image.png](https://images.zenhubusercontent.com/61a121c4a7a3264dfdc530ef/84d5e3d3-cabb-42f1-8d52-1e1764d45050) 

Actual Results : Hard delete of Namespace (/namespaces/{ns}?force=true) cause the application inaccessible (throws 502 Bad Gateway Error). Other API endpoints also throws 502 Gateway error

Expected Result :  Hard delete of Namespace (/namespaces/{ns}?force=true) should not affect any application or services

**Comment by chrsamp** [comment]
Related to #876 

@Elson9 @jTendeck can you try to repro this as well in dev

**Comment by odyeung** [comment]
is this still relevant?

**Comment by odyeung** [comment]
this is still relevant when it comes to gwa-cli command

**Comment by ikethecoder** [comment]
Not quite sure what the diff is between this and #876 , but have made some updates to handle the namespace deletion cleaner.  Also changed the cascading logic so that if there are consumers, it will stop you from deleting the namespace even with the `force=true` option.  Consumers will need to be cleaned up (revoked) before the namespace can be deleted.

@nirajCITZ Can you retest against this feature branch?
